# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Developer Portal"
description: "Queensland Education"
baseurl: # the subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
posts-url: "https://github.com/QED-DeveloperPortal/qed-developerportal.github.io/blob/master"
logo: "/images/dev-portal-header.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"
google_fonts:
  - name: "Open Sans"
    weights: "300,400,400i,700,700i"
  - name: "Esteban"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: dev-portal-qld
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name:
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Site metric values
site_metrics:
  - label: Members
    value: 1023
    icon: fas fa-user
  - label: Quick starts
    value: 28
    icon: fas fa-file-download
  - label: Projects
    value: 289
    icon: fas fa-code-branch
  - label: API endpoints
    value: 64
    icon: fas fa-cog
  - label: Lines of code
    value: 2 million
    icon: fas fa-code
  - label: Comments
    value: 452
    icon: fas fa-comment-dots

# Social Footer Links
social_footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: Facebook
    url: https://www.facebook.com
    icon: fab fa-facebook-f
  - title: Twitter
    url: https://www.twitter.com
    icon: fab fa-twitter
  - title: Youtube
    url: https://www.youtube.com
    icon: fab fa-youtube
  - title: LinkedIn
    url: https://www.instagram.com
    icon: fab fa-instagram
  - title: LinkedIn
    url: https://www.linkedin.com
    icon: fab fa-linkedin-in

# Footer Links
footer_links:
  - title: Copyright
    url: #
  - title: Disclaimer
    url: #
  - title: Privacy
    url: #
  - title: Right to information
    url: https://www.rti.qld.gov.au/
  - title: Accessibility
    url: #
  - title: Jobs in Queensland Government
    url: https://smartjobs.qld.gov.au
  - title: Other languages
    url: https://www.qld.gov.au/help/languages
  - title: Site map
    url: #
